# -*- coding: utf-8 -*-
"""Copy of DL_Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137LwYXPIKxEYEJar-yiiUBforhHaH_iZ

# Question 1

## Setup

First, we define our mathematical surfaces and their exact derivatives.
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from IPython.display import display, Image, HTML
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

# 1. The Bowl (Isotropic)
def bowl(x, y): return x**2 + y**2
def grad_bowl(x, y): return np.array([2*x, 2*y])

# 2. The Ravine (Anisotropic)
def ravine(x, y): return x**2 + 200*y**2
def grad_ravine(x, y): return np.array([2*x, 400*y])

# 3. The Saddle
def saddle(x, y): return x**2 - y**2
def grad_saddle(x, y): return np.array([2*x, -2*y])

surfaces = {
    'Bowl':   {'f': bowl,   'g': grad_bowl,   'start': np.array([-4.0, 4.0]),   'lr': 0.05,  'bounds': (-5, 5, -5, 5)},
    'Ravine': {'f': ravine, 'g': grad_ravine, 'start': np.array([-4.0, 3.0]),   'lr': 0.001, 'bounds': (-5, 5, -4, 4)},
    'Saddle': {'f': saddle, 'g': grad_saddle, 'start': np.array([-1.5, 0.001]), 'lr': 0.05,  'bounds': (-3, 3, -3, 3)}
}
print("Cell 1 Executed: Landscapes initialized.")

"""## Unified Optimizer & Theory

Below are the exact mathematical equations implemented in this code for the parameters $w$ (our $x,y$ coordinates), gradients $g$, and learning rate $\eta$:

Gradient Descent (GD): Steps strictly opposite the gradient.$$w_{t+1} = w_t - \eta g_t$$

Momentum: Accumulates a velocity vector $v$ with friction $\beta$ to power through flat areas and dampen zig-zags.$$v_{t+1} = \beta v_t + g_t$$$$w_{t+1} = w_t - \eta v_{t+1}$$

Stochastic Gradient Descent (SGD): Adds Gaussian noise $\xi \sim \mathcal{N}(0, I)$ scaled by $\sigma$ to simulate the variance of calculating gradients on single, random data points.$$w_{t+1} = w_t - \eta (g_t + \sigma \xi)$$

Minibatch SGD: Mathematically identical to SGD, but with a smaller $\sigma$, simulating the reduced variance of taking a small "batch" of data points.

Adam (Adaptive Moment Estimation): Maintains a rolling average of the gradient $m_t$ (momentum) and the squared gradient $v_t$ (variance). It scales the step size individually for $x$ and $y$ based on historical steepness. Bias corrections $\hat{m}_t$ and $\hat{v}_t$ prevent slow starts.$$m_t = \beta_1 m_{t-1} + (1 - \beta_1) g_t$$$$v_t = \beta_2 v_{t-1} + (1 - \beta_2) g_t^2$$$$\hat{m}_t = \frac{m_t}{1 - \beta_1^t}, \quad \hat{v}_t = \frac{v_t}{1 - \beta_2^t}$$$$w_{t+1} = w_t - \eta \frac{\hat{m}_t}{\sqrt{\hat{v}_t} + \epsilon}$$
"""

def optimize(opt_name, grad_fn, start_pt, initial_lr, max_steps=1000):
    pos = start_pt.copy()
    trajectory = [pos.copy()]
    lr = initial_lr

    v = np.zeros(2)
    m = np.zeros(2)
    v_adam = np.zeros(2)

    beta = 0.9
    beta1, beta2 = 0.9, 0.999
    eps = 1e-8
    sigma_sgd = 0.5
    sigma_mb = 0.15

    step = 0
    while step < max_steps:
        step += 1
        g = grad_fn(pos[0], pos[1])

        if opt_name == 'GD':
            update = -lr * g
        elif opt_name == 'Momentum':
            v = beta * v + g
            update = -lr * v
        elif opt_name == 'SGD':
            noise = np.random.randn(2) * sigma_sgd
            update = -lr * (g + noise)
        elif opt_name == 'Minibatch-SGD':
            noise = np.random.randn(2) * sigma_mb
            update = -lr * (g + noise)
        elif opt_name == 'Adam':
            m = beta1 * m + (1 - beta1) * g
            v_adam = beta2 * v_adam + (1 - beta2) * (g**2)
            m_hat = m / (1 - beta1**step)
            v_hat = v_adam / (1 - beta2**step)
            update = -(lr * 10) * m_hat / (np.sqrt(v_hat) + eps)

        next_pos = pos + update

        # Divergence safety net
        if np.any(np.abs(next_pos) > 1e3) or np.any(np.isnan(next_pos)):
            lr *= 0.5
            step -= 1
            continue

        pos = next_pos
        trajectory.append(pos.copy())

    return np.array(trajectory)
print("Cell 2 Executed: Optimizer engine and math rules ready.")

"""## Visualizaition

This cell contains the helper functions to build the GIFs and calculate whether an algorithm successfully solved the landscape.
"""

def evaluate_performance(traj, surface_name):
    if surface_name in ['Bowl', 'Ravine']:
        dists = np.linalg.norm(traj, axis=1)
        converged = np.any(dists < 0.1)
        steps = np.argmax(dists < 0.1) if converged else 1000
        # FIX: Dynamically set the status string based on convergence
        status = "Reached Min" if converged else "Did Not Converge"
        return status, steps if converged else ">1000"
    else:  # Saddle
        # FIX: Start point is (-1.5, 0.001). The x-coordinate is already at -1.5,
        # so checking if |x| > 0.5 triggers on step 0. We must only check the y-axis
        # (the unstable direction) to see if it actually falls off the saddle.
        threshold = 0.1
        escaped = np.any(np.abs(traj[:, 1]) > threshold)
        if escaped:
            steps = np.argmax(np.abs(traj[:, 1]) > threshold)
            status = "Escaped"
        else:
            steps = 1000
            status = "Stuck"
        return status, steps if escaped else ">1000"

def create_gif(surface_name, results_dict, filename):
    s_data = surfaces[surface_name]
    fig, ax = plt.subplots(figsize=(7, 6))

    xmin, xmax, ymin, ymax = s_data['bounds']
    X, Y = np.meshgrid(np.linspace(xmin, xmax, 100), np.linspace(ymin, ymax, 100))
    Z = s_data['f'](X, Y)

    levels = np.linspace(-10, 10, 30) if surface_name == 'Saddle' else np.logspace(-1, 3, 20)
    cmap = 'coolwarm' if surface_name == 'Saddle' else 'viridis'
    ax.contour(X, Y, Z, levels=levels, cmap=cmap, alpha=0.5)

    ax.set_title(f'Optimizers on {surface_name}')
    ax.set_xlim(xmin, xmax); ax.set_ylim(ymin, ymax)

    colors = {'GD': 'black', 'Momentum': 'blue', 'SGD': 'red', 'Minibatch-SGD': 'orange', 'Adam': 'green'}
    scatters, lines = {}, {}
    opts = list(results_dict.keys())

    for opt in opts:
        scatters[opt] = ax.scatter([], [], c=colors[opt], s=40, label=opt, zorder=5)
        lines[opt], = ax.plot([], [], c=colors[opt], alpha=0.3, zorder=4)

    ax.legend(loc='upper right')
    step_text = ax.text(0.05, 0.95, '', transform=ax.transAxes, fontsize=12, fontweight='bold')

    def init():
        for opt in opts:
            scatters[opt].set_offsets(np.empty((0, 2)))
            lines[opt].set_data([], [])
        return list(scatters.values()) + list(lines.values()) + [step_text]

    def update(frame):
        idx = min(frame * 1, 1000)
        for opt in opts:
            traj = results_dict[opt]
            curr_idx = min(idx, len(traj)-1)
            scatters[opt].set_offsets(traj[curr_idx])
            lines[opt].set_data(traj[:curr_idx+1, 0], traj[:curr_idx+1, 1])
        step_text.set_text(f'Step: {idx}')
        return list(scatters.values()) + list(lines.values()) + [step_text]

    anim = animation.FuncAnimation(fig, update, frames=1001, init_func=init, blit=True, interval=50)
    anim.save(filename, writer='pillow', fps=15)
    plt.close(fig)
    return filename

master_results = []
opts = ['GD', 'Momentum', 'SGD', 'Minibatch-SGD', 'Adam']
print("Cell 3 Executed: Evaluation and GIF engine ready.")

"""## Exp 1: The Bowl

The Bowl is symmetrical, meaning the gradient always points directly to the center $(0,0)$.

- Black (GD): Moves in a perfectly straight line directly to the center and stops.

- Blue (Momentum): Builds up velocity. Because it has mass, it can't stop instantly at the center; it overshoots the minimum and spirals back in, like a marble settling in a physical bowl.

- Red (SGD): The injected noise causes it to jitter violently. It reaches the center but can never settle there; it orbits the minimum chaotically.

- Orange (Minibatch-SGD): Shows the same jitter as SGD, but tighter and more controlled.

- Green (Adam): Takes a slightly curved, deliberate path, aggressively damping out its own momentum as it nears the center.
"""

s_name = 'Bowl'
np.random.seed(42)
bowl_results = {}

for opt in opts:
    traj = optimize(opt, surfaces[s_name]['g'], surfaces[s_name]['start'], surfaces[s_name]['lr'])
    bowl_results[opt] = traj
    status, steps = evaluate_performance(traj, s_name)
    master_results.append({'Surface': s_name, 'Optimizer': opt, 'Status': status, 'Steps': steps})

gif_name = f"{s_name}.gif"
create_gif(s_name, bowl_results, gif_name)
display(Image(filename=gif_name))

"""## Exp 2: The Ravine

The Ravine is extremely steep along the $y$-axis and almost entirely flat along the $x$-axis. This is the ultimate trap for naïve algorithms.

- Black (GD): Plunges down the steep $y$-wall and immediately bounces to the opposite wall. Because the $x$-gradient is so weak, it makes almost zero forward progress. It gets stuck zig-zagging.

- Red/Orange (SGD variants): Their inherent noise makes the zig-zagging even worse. They fail entirely to navigate the narrow canyon.

- Green (Adam): While theoretically well-suited for anisotropic ravines, Adam times out (>1000 steps) in our setup. Because Adam normalizes its step sizes, its maximum velocity is constrained by the very small learning rate (lr=0.001). It crawls too slowly to finish in time.

- Blue (Momentum): The absolute winner here (153 steps). It starts by zig-zagging, but the $x$-velocity compounds over time, while the alternating $y$-velocities cancel each other out. Unconstrained by Adam's normalization, Momentum leverages the raw gradients to rocket down the canyon.
"""

s_name = 'Ravine'
np.random.seed(42)
ravine_results = {}

for opt in opts:
    traj = optimize(opt, surfaces[s_name]['g'], surfaces[s_name]['start'], surfaces[s_name]['lr'])
    ravine_results[opt] = traj
    status, steps = evaluate_performance(traj, s_name)
    master_results.append({'Surface': s_name, 'Optimizer': opt, 'Status': status, 'Steps': steps})

gif_name = f"{s_name}.gif"
create_gif(s_name, ravine_results, gif_name)
display(Image(filename=gif_name))

"""## The Saddle and final data printing

A saddle point is a plateau. If you move along the $y$-axis it goes down, but along the $x$-axis it goes up. We start at $y=0.001$, meaning we are balanced on a knife-edge where the gradient is practically zero.

- Black (GD): Escapes the slowest (49 steps). Because the initial downward slope along the $y$-axis is microscopic at your starting point ($y=0.001$), GD takes dozens of tiny steps before it falls far enough down the slope to accelerate.
- Blue (Momentum): Escapes much faster (19 steps). The built-up velocity compounds those tiny initial steps, pushing the optimizer off the plateau more than twice as fast as standard GD.
- Red/Orange (SGD variants): Escape quickly (19 and 18 steps). For saddle points, noise is highly beneficial. The random jitter immediately kicks the optimizers off the delicately balanced center line, exposing them to the steeper downward slopes on the sides.
- Green (Adam): Escapes instantly (1 step). Because Adam divides its step size by the historical squared gradient, it detects the near-zero slope, normalizes it, and takes a massively scaled leap straight off the saddle point on the very first try.
"""

s_name = 'Saddle'
np.random.seed(42)
saddle_results = {}

for opt in opts:
    traj = optimize(opt, surfaces[s_name]['g'], surfaces[s_name]['start'], surfaces[s_name]['lr'])
    saddle_results[opt] = traj
    status, steps = evaluate_performance(traj, s_name)
    master_results.append({'Surface': s_name, 'Optimizer': opt, 'Status': status, 'Steps': steps})

gif_name = f"{s_name}.gif"
create_gif(s_name, saddle_results, gif_name)
display(Image(filename=gif_name))

print("\n" + "="*50)
print("FINAL CONVERGENCE REPORT")
print("="*50)
df = pd.DataFrame(master_results)
display(df)

"""# Question 2

## Rosenbrock Math and Setup

The Rosenbrock surface is defined as:$$L(x,y) = (1 - x)^2 + 100(y - x^2)^2$$

To optimize it, we need its exact derivatives with respect to $x$ and $y$. Using the chain rule:$$\frac{\partial L}{\partial x} = -2(1 - x) - 400x(y - x^2)$$$$\frac{\partial L}{\partial y} = 200(y - x^2)$$The global minimum is exactly at $(1, 1)$, where the loss becomes $0$. The surface features a long, incredibly narrow, and curved parabolic valley.
"""

# 1. Define the Rosenbrock Function and Gradient
def rosenbrock(x, y):
    return (1 - x)**2 + 100 * (y - x**2)**2

def grad_rosenbrock(x, y):
    dx = -2 * (1 - x) - 400 * x * (y - x**2)
    dy = 200 * (y - x**2)
    return np.array([dx, dy])

# 2. Add to our surfaces dictionary
surfaces['Rosenbrock'] = {
    'f': rosenbrock,
    'g': grad_rosenbrock,
    'start': np.array([-1.5, 1.5]),
    # We use a very small LR here. The gradients on the walls are massive.
    'lr': 0.002,
    'bounds': (-2.5, 2.5, -1.0, 3.5)
}

# 3. Custom evaluator (since the minimum is at (1,1), not (0,0))
def evaluate_rosenbrock(traj):
    target = np.array([1.0, 1.0])
    dists = np.linalg.norm(traj - target, axis=1)
    converged = np.any(dists < 0.1)
    steps = np.argmax(dists < 0.1) if converged else 1000
    return "Reached Min" if converged else "Stuck/Oscillating", steps if converged else ">1000"

print("Rosenbrock initialized.")

"""## Simulation

- Black (GD): Immediately hits the wall of the curved valley and gets trapped. The steep walls force it to bounce back and forth, making almost zero forward progress along the actual curve towards $(1,1)$.
- Red/Orange (SGD variants): Completely hopeless here. The valley is so narrow that any added random noise instantly throws them high up the steep walls, destroying any progress.
- Green (Adam): Struggles and gets stuck/oscillating. Similar to the Ravine, the tiny learning rate (lr=0.002) restricts Adam's step size. It simply cannot cover enough ground to navigate the long, curved valley within 1000 steps.
- Blue (Momentum): Performs incredibly well, reaching the minimum in just 20 steps. The built-up momentum dampens the wall-bouncing and propels it rapidly along the valley floor.
"""

s_name = 'Rosenbrock'
np.random.seed(42)
rosenbrock_results = {}
rosenbrock_table = []

for opt in opts:
    # We use the unified optimize function from Cell 2
    traj = optimize(opt, surfaces[s_name]['g'], surfaces[s_name]['start'], surfaces[s_name]['lr'])
    rosenbrock_results[opt] = traj

    status, steps = evaluate_rosenbrock(traj)
    rosenbrock_table.append({'Surface': s_name, 'Optimizer': opt, 'Status': status, 'Steps': steps})

# Create the GIF using the function from Cell 3
gif_name = f"{s_name}.gif"
create_gif(s_name, rosenbrock_results, gif_name)
display(Image(filename=gif_name))

# Display the Table
print("\n" + "="*50)
print("ROSENBROCK CONVERGENCE REPORT")
print("="*50)
df_rosenbrock = pd.DataFrame(rosenbrock_table)
display(df_rosenbrock)

"""The Rosenbrock function is notoriously difficult to optimize compared to the Bowl, Ravine, and Saddle because it combines severe anisotropy (like the Ravine) with a non-linear, curved valley.

- Compared to the Bowl: The Bowl is perfectly isotropic. The gradient always points directly at the global minimum. All optimizers (except the noisy SGD variants) can follow a straight line to the solution. In Rosenbrock, the gradient almost never points at the global minimum; it points sharply down toward the valley floor.
- Compared to the Saddle: A saddle point is a localized trap. Once an optimizer finds the downward slope (the unstable $y$-axis), it accelerates away easily. Rosenbrock is a continuous trap; the optimizer must constantly navigate steep, threatening walls for the entire duration of its descent.
- Compared to the Ravine: While both the Ravine and Rosenbrock feature a narrow valley with massive gradients on the walls and tiny gradients along the floor, the Ravine's valley is perfectly straight. Momentum can easily accumulate velocity along a straight line. Rosenbrock's valley is parabolic (curved).

### Inference on Optimizers
- Gradient Descent (GD) & SGD: These struggle the most, completely failing to converge. Because the gradient on the walls is so much larger than the gradient along the valley, GD takes steps almost entirely perpendicular to the optimal path, resulting in endless zig-zagging.
- Adam: While Adam is designed to adapt to ravines by scaling axes independently, it struggles on Rosenbrock in our specific test due to hyperparameter sensitivity. Because Rosenbrock requires navigating a long distance, Adam's normalized steps (capped by a low learning rate) cause it to crawl and time out.
- Momentum: In our results, Momentum handled Rosenbrock the best. It succeeds because the moving average of the gradients cancels out the perpendicular zig-zags (wall-bouncing) while accumulating speed in the direction of the valley. However, even Momentum is at risk on Rosenbrock: if it builds too much speed, the curvature of the valley will cause it to overshoot and slam into the outer wall of the "banana" shape.

# Question 3

Learning-rate schedule functions
"""

import numpy as np

def lr_constant(t, eta0=0.002, **kwargs):
    """Constant learning rate: η_t = η0"""
    return eta0


def lr_step_decay(t, eta0=0.002, K=200, **kwargs):
    """Step decay: η_t = η0 * 0.1^(floor(t / K))"""
    return eta0 * (0.1 ** (t // K))


def lr_exponential_decay(t, eta0=0.002, gamma=0.995, **kwargs):
    """Exponential decay: η_t = η0 * gamma^t"""
    return eta0 * (gamma ** t)


def lr_cosine_annealing(t, eta0=0.002, eta_min=1e-5, T=1000, **kwargs):
    """Cosine annealing: η_t = η_min + 0.5*(η0 - η_min)*(1 + cos(π t / T))"""
    return eta_min + 0.5 * (eta0 - eta_min) * (1 + np.cos(np.pi * t / T))


def lr_warmup_cosine_decay(t, eta0=0.002, eta_min=1e-5, T=1000, T_warmup=100, **kwargs):
    """Linear warmup + cosine decay."""
    if t <= T_warmup:
        # Linear warmup from 0 to eta0
        return (t / T_warmup) * eta0
    else:
        # Cosine decay from eta0 to eta_min over [T_warmup, T]
        return eta_min + 0.5 * (eta0 - eta_min) * (
            1 + np.cos(np.pi * (t - T_warmup) / (T - T_warmup))
        )


schedules = {
    "Constant": lr_constant,
    "Step Decay": lr_step_decay,
    "Exponential Decay": lr_exponential_decay,
    "Cosine Annealing": lr_cosine_annealing,
    "Warmup + Cosine": lr_warmup_cosine_decay,
}

"""2. Adam optimizer with schedule"""

def optimize_adam_with_schedule(
    grad_fn,
    start_pt,
    schedule_fn,
    max_steps=1000,
    schedule_kwargs=None,
    bounds=None,
    max_radius=50.0,
):
    """
    Adam with a time-varying learning rate schedule.
    schedule_fn(t, **schedule_kwargs) -> eta_t
    """
    if schedule_kwargs is None:
        schedule_kwargs = {}

    pos = start_pt.copy()
    trajectory = [pos.copy()]
    lr_history = []

    m = np.zeros(2)
    v_adam = np.zeros(2)
    beta1, beta2 = 0.9, 0.999
    eps = 1e-8

    for step in range(1, max_steps + 1):
        g = grad_fn(pos[0], pos[1])

        # Learning rate at this step
        eta_t = schedule_fn(step - 1, **schedule_kwargs)  # t = 0..max_steps-1
        lr_history.append(eta_t)

        # Adam update
        m = beta1 * m + (1 - beta1) * g
        v_adam = beta2 * v_adam + (1 - beta2) * (g**2)
        m_hat = m / (1 - beta1**step)
        v_hat = v_adam / (1 - beta2**step)
        update = -eta_t * m_hat / (np.sqrt(v_hat) + eps)

        next_pos = pos + update

        # Divergence / off-screen check
        if bounds is not None:
            xmin, xmax, ymin, ymax = bounds
            margin = 1.5
            off_screen = (
                next_pos[0] < xmin * margin or next_pos[0] > xmax * margin or
                next_pos[1] < ymin * margin or next_pos[1] > ymax * margin or
                np.any(np.isnan(next_pos))
            )
        else:
            off_screen = np.linalg.norm(next_pos) > max_radius or np.any(np.isnan(next_pos))

        if off_screen:
                # Halve base LR and restart
                eta0 *= 0.5
                halvings += 1
                diverged = True
                break

        pos = next_pos
        trajectory.append(pos.copy())

    return np.array(trajectory), np.array(lr_history)

"""Run all schedules on Rosenbrock"""

import matplotlib.pyplot as plt

s_name = "Rosenbrock"
base_lr = 0.002
T = 1000

schedule_kwargs_base = {
    "eta0": base_lr,
    "T": T,
    "eta_min": 1e-5,
    "K": 200,       # for step decay
    "gamma": 0.995, # for exponential
    "T_warmup": 100,
}

results_schedules = {}  # name -> {"traj": ..., "lr": ..., "loss": ...}

for name, sched_fn in schedules.items():
    traj, lr_hist = optimize_adam_with_schedule(
        grad_fn=surfaces[s_name]["g"],
        start_pt=surfaces[s_name]["start"],
        schedule_fn=sched_fn,
        max_steps=T,
        schedule_kwargs=schedule_kwargs_base,
        bounds=surfaces[s_name]["bounds"],
    )
    # Compute loss at each step
    losses = np.array([surfaces[s_name]["f"](p[0], p[1]) for p in traj])

    results_schedules[name] = {
        "traj": traj,
        "lr": lr_hist,
        "loss": losses,
    }

for name, data in results_schedules.items():
    print(
        name,
        "Final position:", data["traj"][-1],
        "Final loss:", data["loss"][-1]
    )

"""GIF: trajectories on Rosenbrock + η_t curves

Trajectories on Rosenbrock (single GIF)
"""

import matplotlib.animation as animation
from IPython.display import display, Image

def create_gif_schedules(surface_name, results_dict, filename):
    s_data = surfaces[surface_name]
    fig, ax = plt.subplots(figsize=(7, 6))

    xmin, xmax, ymin, ymax = s_data['bounds']
    X, Y = np.meshgrid(np.linspace(xmin, xmax, 100), np.linspace(ymin, ymax, 100))
    Z = s_data['f'](X, Y)

    # Contours
    levels = np.logspace(-1, 3, 20)
    ax.contour(X, Y, Z, levels=levels, cmap='viridis', alpha=0.5)

    ax.set_title(f'Adam with LR Schedules on {surface_name}')
    ax.set_xlim(xmin, xmax)
    ax.set_ylim(ymin, ymax)

    colors = {
        "Constant": "black",
        "Step Decay": "blue",
        "Exponential Decay": "red",
        "Cosine Annealing": "orange",
        "Warmup + Cosine": "green",
    }

    sched_names = list(results_dict.keys())
    scatters, lines = {}, {}

    for name in sched_names:
        scatters[name] = ax.scatter([], [], c=colors[name], s=40, label=name, zorder=5)
        lines[name], = ax.plot([], [], c=colors[name], alpha=0.3, zorder=4)

    ax.legend(loc='upper right')
    step_text = ax.text(0.05, 0.95, '', transform=ax.transAxes, fontsize=12, fontweight='bold')

    def init():
        for name in sched_names:
            scatters[name].set_offsets(np.empty((0, 2)))
            lines[name].set_data([], [])
        return list(scatters.values()) + list(lines.values()) + [step_text]

    def update(frame):
        idx = min(frame, T)
        for name in sched_names:
            traj = results_dict[name]["traj"]
            curr_idx = min(idx, len(traj) - 1)
            scatters[name].set_offsets(traj[curr_idx])
            lines[name].set_data(traj[:curr_idx+1, 0], traj[:curr_idx+1, 1])
        step_text.set_text(f'Step: {idx}')
        return list(scatters.values()) + list(lines.values()) + [step_text]

    anim = animation.FuncAnimation(fig, update, frames=T+1, init_func=init, blit=True, interval=50)
    anim.save(filename, writer='pillow', fps=15)
    plt.close(fig)
    return filename

gif_name = "Rosenbrock_schedules.gif"
create_gif_schedules(s_name, results_schedules, gif_name)
display(Image(filename=gif_name))

"""Plot: η_t curves for each schedule"""

plt.figure(figsize=(8, 5))
for name, data in results_schedules.items():
    lr_hist = data["lr"]
    plt.plot(lr_hist, label=name)

plt.xlabel("Step")
plt.ylabel("Learning rate η_t")
plt.title("Learning-rate schedules over time")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""Plot: loss vs step for each schedule"""

plt.figure(figsize=(8, 5))
for name, data in results_schedules.items():
    losses = data["loss"]
    plt.plot(losses, label=name)

plt.xlabel("Step")
plt.ylabel("Loss L(x,y)")
plt.title("Loss vs Step for Different LR Schedules on Rosenbrock")
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""The five learning-rate schedules were evaluated using Adam on the Rosenbrock surface for 1000 steps. Among the tested schedules, the constant learning rate achieved the lowest final loss of 5.195, followed by cosine annealing (5.270), warmup + cosine (5.284), step decay (5.307), and exponential decay (5.317). The constant learning rate therefore performed best for the chosen hyperparameters. None of the schedules reached the global minimum within 1000 steps, indicating that the chosen learning-rate scale was relatively conservative for the Rosenbrock landscape.

The warmup + cosine schedule started with a learning rate of zero and gradually increased it, resulting in slower initial progress than the other schedules. In this experiment, warmup did not improve the final performance compared with cosine annealing or the constant learning rate.

# Question 4
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms
from sklearn.metrics import accuracy_score, f1_score

# Setting up the configuration
# (I have denoted the global constant values with variables in all CAPs)
SEED = 42

torch.manual_seed(SEED)
np.random.seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("Using device:", DEVICE)

EPOCHS = 50
BATCH_SIZE = 64
LEARNING_RATE = 1e-3

TRAIN_SIZE = 5000
TEST_SIZE = 1000

DROPOUT_VALUES = [0.0, 0.1, 0.25, 0.5, 0.75]

# Loading Fashion MNIST
transform = transforms.ToTensor()

train_dataset_full = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=transform
)

test_dataset_full = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=transform
)


# Using the same fixed subset for every experiment
train_dataset = Subset(
    train_dataset_full,
    range(TRAIN_SIZE)
)

test_dataset = Subset(
    test_dataset_full,
    range(TEST_SIZE)
)


train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False
)

# Defining the MLP
class FashionMLP(nn.Module):
    def __init__(self, dropout=0.0):
        super().__init__()
        self.network = nn.Sequential(
            nn.Flatten(),
            nn.Linear(28 * 28, 256),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, 10)
        )

    def forward(self, x):
        return self.network(x)

# Setting up the Evaluation function
def evaluate(model, loader, criterion):
    model.eval()
    total_loss = 0.0
    predictions = []
    targets = []
    with torch.no_grad():
        for images, labels in loader:
            images = images.to(DEVICE)
            labels = labels.to(DEVICE)
            outputs = model(images)
            loss = criterion(outputs, labels)
            total_loss += loss.item() * images.size(0)
            preds = torch.argmax(outputs, dim=1)
            predictions.extend(preds.cpu().numpy())
            targets.extend(labels.cpu().numpy())
    loss = total_loss / len(loader.dataset)
    accuracy = accuracy_score( targets, predictions)

    f1 = f1_score( targets, predictions, average="macro")

    return loss, accuracy, f1

# Setting up the Train model function
def train_model(dropout):
    print("\n" + "=" * 60)
    print(f"Training model with dropout = {dropout}")
    print("=" * 60)

    model = FashionMLP( dropout=dropout).to(DEVICE)

    criterion = nn.CrossEntropyLoss()

    optimizer = optim.Adam(model.parameters(),lr=LEARNING_RATE)

    history = {
        "train_loss": [],
        "test_loss": [],

        "train_accuracy": [],
        "test_accuracy": [],

        "train_f1": [],
        "test_f1": []
    }

    for epoch in range(EPOCHS):
        # Training
        model.train()
        running_loss = 0.0

        for images, labels in train_loader:

            images = images.to(DEVICE)
            labels = labels.to(DEVICE)

            optimizer.zero_grad()

            outputs = model(images)

            loss = criterion(outputs,labels)

            loss.backward()

            optimizer.step()

            running_loss += ( loss.item() * images.size(0))

        train_loss = (running_loss / len(train_loader.dataset))

        # Evaluating training data
        train_eval_loss, train_accuracy, train_f1 = evaluate(
            model,
            train_loader,
            criterion
        )


        # Evaluating test data
        test_loss, test_accuracy, test_f1 = evaluate(
            model,
            test_loader,
            criterion
        )

        # Storing metrics
        history["train_loss"].append(train_eval_loss)
        history["test_loss"].append(test_loss)

        history["train_accuracy"].append(train_accuracy)
        history["test_accuracy"].append(test_accuracy)

        history["train_f1"].append(train_f1)
        history["test_f1"].append(test_f1)


        print(
            f"Epoch {epoch + 1:02d}/{EPOCHS} | "
            f"Train Acc: {train_accuracy:.4f} | "
            f"Test Acc: {test_accuracy:.4f} | "
            f"Train F1: {train_f1:.4f} | "
            f"Test F1: {test_f1:.4f}"
        )

    return model, history

# Training all the 5 models
models = {}
histories = {}

for dropout in DROPOUT_VALUES:

    model, history = train_model(dropout)

    models[dropout] = model
    histories[dropout] = history

# Ploting accuracy curves
epochs = range(1, EPOCHS + 1)
plt.figure(figsize=(12, 7))

for dropout in DROPOUT_VALUES:

    plt.plot(
        epochs,
        histories[dropout]["train_accuracy"],
        label=f"Train, p={dropout}"
    )

    plt.plot(
        epochs,
        histories[dropout]["test_accuracy"],
        linestyle="--",
        label=f"Test, p={dropout}"
    )

plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.title("FashionMNIST Accuracy vs Epoch")
plt.legend()
plt.grid(True)
plt.tight_layout()

plt.show()

# Plotting F1 curves
plt.figure(figsize=(12, 7))

for dropout in DROPOUT_VALUES:

    plt.plot(
        epochs,
        histories[dropout]["train_f1"],
        label=f"Train, p={dropout}"
    )

    plt.plot(
        epochs,
        histories[dropout]["test_f1"],
        linestyle="--",
        label=f"Test, p={dropout}"
    )

plt.xlabel("Epoch")
plt.ylabel("Macro F1 Score")
plt.title("FashionMNIST Macro-F1 vs Epoch")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Subplots for understanding well
fig, axes = plt.subplots(
    2,
    3,
    figsize=(16, 9)
)

axes = axes.ravel()

for i, dropout in enumerate(DROPOUT_VALUES):

    ax = axes[i]

    ax.plot(
        epochs,
        histories[dropout]["train_accuracy"],
        label="Train Accuracy"
    )

    ax.plot(
        epochs,
        histories[dropout]["test_accuracy"],
        label="Test Accuracy"
    )

    ax.plot(
        epochs,
        histories[dropout]["train_f1"],
        linestyle="--",
        label="Train F1"
    )

    ax.plot(
        epochs,
        histories[dropout]["test_f1"],
        linestyle="--",
        label="Test F1"
    )

    ax.set_title(
        f"Dropout p = {dropout}"
    )

    ax.set_xlabel("Epoch")
    ax.set_ylabel("Score")
    ax.grid(True)
    ax.legend(fontsize=8)

# Remove unused sixth subplot
fig.delaxes(axes[-1])

plt.tight_layout()
plt.show()

results = []
for dropout in DROPOUT_VALUES:
    history = histories[dropout]

    final_train_acc = history["train_accuracy"][-1]
    final_test_acc = history["test_accuracy"][-1]

    final_train_f1 = history["train_f1"][-1]
    final_test_f1 = history["test_f1"][-1]

    acc_gap = final_train_acc - final_test_acc
    f1_gap = final_train_f1 - final_test_f1

    best_test_acc = max(
        history["test_accuracy"]
    )

    best_test_acc_epoch = (
        np.argmax(
            history["test_accuracy"]
        ) + 1
    )

    best_test_f1 = max(
        history["test_f1"]
    )

    best_test_f1_epoch = (
        np.argmax(
            history["test_f1"]
        ) + 1
    )

    results.append({

        "Dropout": dropout,

        "Final Train Accuracy": final_train_acc,
        "Final Test Accuracy": final_test_acc,

        "Final Train F1": final_train_f1,
        "Final Test F1": final_test_f1,

        "Accuracy Gap": acc_gap,
        "F1 Gap": f1_gap,

        "Best Test Accuracy": best_test_acc,
        "Best Accuracy Epoch": best_test_acc_epoch,

        "Best Test F1": best_test_f1,
        "Best F1 Epoch": best_test_f1_epoch
    })


results_df = pd.DataFrame(results)

print("\nFinal Results")
print("=" * 100)

print(
    results_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.4f}"
    )
)

best_row = results_df.loc[
    results_df["Best Test F1"].idxmax()
]

print("\nBest Dropout Configuration")
print("=" * 50)

print(
    f"Dropout probability: "
    f"{best_row['Dropout']}"
)

print(
    f"Best test F1: "
    f"{best_row['Best Test F1']:.4f}"
)

print(
    f"Epoch: "
    f"{int(best_row['Best F1 Epoch'])}"
)

"""The training and test curves were plotted for both the plain MLP and the models with different dropout probabilities, with accuracy and macro-F1 score recorded at every epoch. The results show that the models with dropout generally had a smaller difference between training and test performance compared with the model without dropout, indicating reduced overfitting.

Among the tested dropout probabilities (0.1, 0.25, 0.5, and 0.75), dropout of 0.1 performed the best, achieving a best test F1 score of 0.8695 at 21st epoch. As the dropout probability increases, more neurons are randomly disabled during training, which increases regularisation and generally reduces the gap between training and test performance. However, excessively high dropout like 0.75 can make the model underfit because lots off information is removed during training. Thus, a moderate amount of dropout provides a better balance between preventing overfitting and allowing the model to learn effectively.
"""



"""#Question 5"""

!pip install imageio -q

#some library imports
import torch
import numpy as np
import matplotlib.pyplot as plt
import imageio
from IPython.display import Image, display
import pandas as pd
device = torch.device("cpu")
torch.set_default_dtype(torch.float32)

#firstly, we are making a 100*100 grid, then we are making the 2d a 1d array of length 100^2
def make_grid(n=100):
    xs = torch.linspace(0, 1, n) #for the width
    ys = torch.linspace(0, 1, n) #for the height
    gx, gy = torch.meshgrid(xs, ys, indexing="ij") #gx and gy give the x and y cordinate respectively, ij for axis conversion row=x axis
    grid = torch.stack([gx.flatten(), gy.flatten()], dim=1)
    return grid

GRID = make_grid(100)

#sum of the light in the entire room from all the lamp posts at every location on the grid
def brightness(lamps, grid, sigma=0.25):
    """
    lamps: (K, 2) tensor of lamp positions
    grid:  (N, 2) tensor of room points
    returns: (N,) total brightness at each grid point
    """
    #this to get the  pairwise squared distances between every grid point and every lamp
    diff = grid.unsqueeze(1) - lamps.unsqueeze(0)      # each room point is given its own row, each lamp is given its own row, in the shape N, 1, 2
    #this to get the pairwise squared distances between every grid point and every lamp
    #now, next line gives ||p - l||^2 for every (grid point, lamp) pair
    sq_dist = (diff ** 2).sum(dim=2)                    #(N, K)
    B = torch.exp(-sq_dist / (2 * sigma ** 2))          #(N, K) Gaussian brightness per point-lamp pair
    return B.sum(dim=1)                                 # (N, total brightness at a point
#this is to calculate the pairwise exponential proximity penalty
def repulsion(lamps, rho=0.20):
    K = lamps.shape[0]
    total = 0.0
    for i in range(K):
        for j in range(i + 1, K): #for each unique lamp pair
            d2 = ((lamps[i] - lamps[j]) ** 2).sum()
            total = total + torch.exp(-d2 / (2 * rho ** 2))
    return total
#gives net target, its the avg brightness-penalty
def objective(lamps, grid, sigma=0.25, rho=0.20, lam=1.0):
    avg_brightness = brightness(lamps, grid, sigma).mean()
    R = repulsion(lamps, rho)#total clustering penalty
    return avg_brightness - lam * R

def optimize_lamps(n_lamps=3, sigma=0.25, rho=0.20, lam=1.0,
                   steps=300, lr=0.05, seed=42):
    torch.manual_seed(seed)  #fixing randomness for reproducability

    #random parameters wich will get updated later
    raw_lamps = torch.randn(n_lamps, 2, requires_grad=True)
    optimizer = torch.optim.Adam([raw_lamps], lr=lr)

    # scales everything to between 1 and 0
    get_lamps = lambda: torch.sigmoid(raw_lamps)

    init_lamps = get_lamps().detach().clone() #starting points for comparison
    history = [init_lamps] #to store all the positions moved
    J_history = [] #to store the intensities

    for step in range(steps):
        optimizer.zero_grad() #claer gradients from prev steps

        #raw value becomes bounded to 0,1
        current_lamps = get_lamps()
        J = objective(current_lamps, GRID, sigma, rho, lam)
        loss = -J
        loss.backward()
        optimizer.step() #update raw_lamps in the direction that increases J

        #saving the bounded positions
        history.append(current_lamps.detach().clone())
        J_history.append(J.item())

    final_lamps = get_lamps().detach()
    return init_lamps, final_lamps, history, J_history

init_lamps, final_lamps, history, J_history = optimize_lamps(n_lamps=3, seed=0)
print("Initial lamps:\n", init_lamps.numpy())
print("Final lamps:\n", final_lamps.numpy())

#sanity check done to see if the optimizer is working or not,
#Should rise then flatten, this confirms J is being maximized and has converged (or tells you if steps was too few).
#Flat from the start shows a likely a broken gradient. lr too small.
#Jagged, never settles shows lr too high
plt.plot(J_history)
plt.xlabel("step")
plt.ylabel("J")
plt.title("Objective during optimization")
plt.show()

#brightness of map before and after

#converting the grid to 100 *100
def plot_brightness(lamps, sigma=0.25, title="", ax=None):
    n = 100
    B = brightness(lamps, GRID, sigma).reshape(n, n).detach().numpy() #converted to 2d for image and detached for plotting
    if ax is None:
        fig, ax = plt.subplots(figsize=(5, 5))
    im = ax.imshow(B.T, origin="lower", extent=[0, 1, 0, 1], cmap="inferno") #.T is used so that x/y line up correctly
    ax.scatter(lamps[:, 0].detach(), lamps[:, 1].detach(),
               c="cyan", edgecolors="black", s=80, marker="*") #for the lamp positions
    ax.set_title(title)
    return im

fig, axes = plt.subplots(1, 2, figsize=(11, 5))
plot_brightness(init_lamps, title="Before optimization", ax=axes[0])
plot_brightness(final_lamps, title="After optimization", ax=axes[1])
plt.tight_layout()
plt.show()

def make_lamp_gif(history, sigma=0.25, filename="lamps.gif", n_frames=60):
    n = 100
    #subsampling of frames so the gif isn't huge
    idxs = np.linspace(0, len(history) - 1, n_frames).astype(int)
    frames = [] #to hold one rendered image per selected step

    for idx in idxs:
        lamps = history[idx]
        B = brightness(lamps, GRID, sigma).reshape(n, n).detach().numpy()

        fig, ax = plt.subplots(figsize=(5, 5))
        ax.imshow(B.T, origin="lower", extent=[0, 1, 0, 1], cmap="inferno", vmin=0, vmax=3)
        ax.scatter(lamps[:, 0], lamps[:, 1], c="cyan", edgecolors="black", s=100, marker="*")
        ax.set_title(f"step {idx}")
        ax.set_xlim(0, 1); ax.set_ylim(0, 1)

        fig.canvas.draw()
        image = np.frombuffer(fig.canvas.buffer_rgba(), dtype=np.uint8)
        image = image.reshape(fig.canvas.get_width_height()[::-1] + (4,))[:, :, :3]
        frames.append(image)#reshape bytes into (height, width, RGBA), drop alpha channe
        plt.close(fig)

    imageio.mimsave(filename, frames, fps=10)
    return filename

gif_path = make_lamp_gif(history, filename="lamps_3.gif")
display(Image(filename=gif_path))

results = []
for seed in np.random.randint(1, 101, size=6):   # 6 random seeds between 1 and 100
    init, final, hist, Js = optimize_lamps(n_lamps=3, seed=int(seed), steps=300)
    results.append((seed, final, Js[-1]))
    print(f"seed {seed}: final J = {Js[-1]:.4f}")
    print(final.numpy())
    print()

#to show that multiple runs on diff seeds still give the same output for lamp positions
rows = []
for seed, final, Jf in results:
    coords = final.numpy()
    centroid = coords.mean(axis=0)
    dists = np.linalg.norm(coords - centroid, axis=1)        #each lamps distance from the centroid
    dists = np.sort(dists)                                   #sorting so rows are comparable across seeds regardless of lamp order

    row = {"seed": int(seed), "J": round(float(Jf), 4),
           "centroid_x": round(centroid[0], 3), "centroid_y": round(centroid[1], 3)}
    for i, d in enumerate(dists, 1):
        row[f"dist_L{i}"] = round(float(d), 3)               #sorted lamp-to-centroid distances
    rows.append(row)

df = pd.DataFrame(rows)
display(df)

# report : check how much J and the centroid/distance pattern vary across seeds
J_spread = df["J"].max() - df["J"].min()
centroid_spread = np.linalg.norm(df[["centroid_x","centroid_y"]].values -
                                  df[["centroid_x","centroid_y"]].values.mean(axis=0), axis=1).max()

print(f"Across {len(df)} seeds: J ranges {df['J'].min():.4f}-{df['J'].max():.4f} "
      f"(spread={J_spread:.4f}), max centroid deviation={centroid_spread:.3f} -> "
      f"{'all the random seeds give the same layout, with L1 and L2 being the distance from centroid to lamp' if J_spread < 0.01 and centroid_spread < 0.05 else 'seeds converge to different layouts'}")

#now, doing for more lamps
for k in [4, 6, 8]:
    init_k, final_k, hist_k, J_k = optimize_lamps(n_lamps=k, steps=400, seed=0)
    print(f"n_lamps={k}, final J={J_k[-1]:.4f}")

    #comparative plots
    fig, axes = plt.subplots(1, 2, figsize=(11, 5))
    plot_brightness(init_k, title=f"Before ({k} lamps)", ax=axes[0])
    plot_brightness(final_k, title=f"After ({k} lamps)", ax=axes[1])
    plt.tight_layout()
    plt.show()

    gif_path = make_lamp_gif(hist_k, filename=f"lamps_{k}.gif")
    display(Image(filename=gif_path))

"""We have used LLMs for making the plots and GIFs more user friendly and understandbale"""